// authorizations_url: "https://api.github.com/authorizations"
// code_search_url: "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}"
// commit_search_url: "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}"
// current_user_authorizations_html_url: "https://github.com/settings/connections/applications{/client_id}"
// current_user_repositories_url: "https://api.github.com/user/repos{?type,page,per_page,sort}"
// current_user_url: "https://api.github.com/user"
// emails_url: "https://api.github.com/user/emails"
// emojis_url: "https://api.github.com/emojis"
// events_url: "https://api.github.com/events"
// feeds_url: "https://api.github.com/feeds"
// followers_url: "https://api.github.com/user/followers"
// following_url: "https://api.github.com/user/following{/target}"
// gists_url: "https://api.github.com/gists{/gist_id}"
// hub_url: "https://api.github.com/hub"
// issue_search_url: "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}"
// issues_url: "https://api.github.com/issues"
// keys_url: "https://api.github.com/user/keys"
// label_search_url: "https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}"
// notifications_url: "https://api.github.com/notifications"
// organization_repositories_url: "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}"
// organization_url: "https://api.github.com/orgs/{org}"
// public_gists_url: "https://api.github.com/gists/public"
// rate_limit_url: "https://api.github.com/rate_limit"
// repository_search_url: "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}"
// repository_url: "https://api.github.com/repos/{owner}/{repo}"
// starred_gists_url: "https://api.github.com/gists/starred"
// starred_url: "https://api.github.com/user/starred{/owner}{/repo}"
// team_url: "https://api.github.com/teams"
// user_organizations_url: "https://api.github.com/user/orgs"
// user_repositories_url: "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}"
// user_search_url: "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
// user_url: "https://api.github.com/users/{user}"


// avatar_url: "https://avatars3.githubusercontent.com/u/38656622?v=4"
// bio: null
// blog: ""
// company: null
// created_at: "2018-04-23T11:24:05Z"
// email: null
// events_url: "https://api.github.com/users/de-leviossa/events{/privacy}"
// followers: 0
// followers_url: "https://api.github.com/users/de-leviossa/followers"
// following: 0
// following_url: "https://api.github.com/users/de-leviossa/following{/other_user}"
// gists_url: "https://api.github.com/users/de-leviossa/gists{/gist_id}"
// gravatar_id: ""
// hireable: null
// html_url: "https://github.com/de-leviossa"
// id: 38656622
// location: null
// login: "de-leviossa"
// name: null
// node_id: "MDQ6VXNlcjM4NjU2NjIy"
// organizations_url: "https://api.github.com/users/de-leviossa/orgs"
// public_gists: 0
// public_repos: 1
// received_events_url: "https://api.github.com/users/de-leviossa/received_events"
// repos_url: "https://api.github.com/users/de-leviossa/repos"
// site_admin: false
// starred_url: "https://api.github.com/users/de-leviossa/starred{/owner}{/repo}"
// subscriptions_url: "https://api.github.com/users/de-leviossa/subscriptions"
// type: "User"
// updated_at: "2019-11-07T08:09:25Z"
// url: "https://api.github.com/users/de-leviossa"